### PR TITLE
Allows the include option to be a single object in populate hook

### PR DESCRIPTION
**Pull request by bertho-zero**
Allows the include option to be a single object

### CODE REVIEW

**Comment by eddyystop** [comment]
Nice. Thanks.

Perhaps this should be implemented for `include` at any depth. The alternatives seem to be

- Add similar code at the end of `populateAddChild` so depths > 1 are handled.
- Handle all depths in `populateItemArray`, returning `items` if there is no `include`.

**Comment by bertho-zero** [comment]
It's done, I added one test but phpstorm did anything with indentation..

**Comment by eddyystop** [comment]
The files are being reorganized in feathers-hooks-common for event filter and permissions filters. I'm holding off on this PR until that settles down.

**Comment by eddyystop** [comment]
First, sorry for the long wait on this PR. I was waiting on another PR that had to be pushed first to prevent merge conflicts arising.

The populate hook change looks great. Thanks!

The original tests tested `include: { {}, {}, ... }`. Those tests now appear to have been converted to only test for `include: {}` rather than to test for that in addition.

Since there's now a speed issue with the module reorganization, perhaps I should make a new PR containing your hook changes for the new module name. Plus I'll include your changed tests as new tests.

**Comment by eddyystop** [comment]
See https://github.com/feathersjs/feathers-hooks-common/pull/88

bertho-zero , thanks for making the above trivial!

**Pull request closed without merging**
