### PR TITLE
Working around another Babel-core 6.17.0 transpilation error in iffElse

### PR DESCRIPTION
**Pull request by eddyystop**
- Only new module changed as old will be deleted soon.
- They caused the  wrong 'this' being passed to predicate and hooks.
- @daffl says transpile is OK in Babel-core 6.21.0
- Added tests to catch any problems in predicate and hooks
- Babel-core 16.7.0 transpiles
const check = typeof predicate === 'function' ? predicate(...fnArgs) : !!predicate;
as
var check = typeof predicate === 'function' ? predicate.apply(undefined, fnArgs) : !!predicate;

### CODE REVIEW

**Comment by daffl** [comment]
What should the context be? In strict mode, the context of a function should be `undefined` when called like this. I'd also try and use the latest versions (clear cache and reinstall) in case it was a bug that has been fixed. I think Babel is around 6.20 now.

**Comment by daffl** [comment]
I'm mainly asking because we might be fixing a non-issue. E.g. when using arrow functions at the module level scope, the context should always be `undefined` (which is why I don't like using top level arrow functions).

**Comment by eddyystop** [comment]
The containing function is a top-level arrow functions. Thanks!

I have a bunch of PRs I'd like to push in order to avoid merge conflicts. So I suggest we push this PR for its tests and then I'll confirm the issue's with the top-level being an arrow function, as the details are a bit more complicated.

**Comment by daffl** [comment]
Sounds good. 👍

**Comment by ekryski** [comment]
Sounds good. :shipit: Let us know if that is still in an issue with Babel v6.20.

**Pull request merged**
