### PR TITLE
Fix #30 (allow all hooks) and #44 (arrow function can't reference this)

### LINKED ISSUE #30: Allow softDelete on all methods
Not just remove & find.

### PR DESCRIPTION
**Pull request by KidkArolis**
Will try to add some tests as well.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you, that definitely makes sense. Looks like that one doesn't have any tests which is probably why it slipped through.

**Comment by daffl** [comment]
Thank you, that definitely makes sense. Looks like that one doesn't have any tests which is probably why it slipped through.

**Comment by eddyystop** [comment]
@KidkArolis Thanks for the catch! Would you mind changing the `!=` to `!==` so the lint passes? Otherwise I can do it later today.

The other hooks are tested with fakes which weren't up to handling this hook. A test would be welcome or i can make one in a day or so.

**Comment by KidkArolis** [comment]
fix linting

**Pull request merged**
