### PR TITLE
Fixed bug in replaceItems involving hook.result.total

### PR DESCRIPTION
**Pull request by eddyystop**
Fixed this issue https://github.com/feathersjs/feathers-hooks-common/issues/93

### CODE REVIEW

**Comment by eddyystop** [comment]
daffl said ok in slack

**Comment by mvandiest** [comment]
Thx for the fix. I see this was merged to master, when will this be published to npm? Last publish was over a month ago.

**Comment by eddyystop** [comment]
v3 should be published this week.

It contains some breaking changes, so its been held back to come out with the Auk release.

**Comment by mvandiest** [comment]
Thx for the update!

**Comment by dottodot** [comment]
Any idea when this will be available?

**Comment by daffl** [comment]
It is in v3.0.0-pre.1

**Comment by dottodot** [comment]
I have tried installing this version but it didn't make any difference, not sure I missing something though. I just did `npm i feathers-hooks-common@3.0.0-pre.1`

**Comment by eddyystop** [comment]
`replace-items` no longer touches `hook.result.total`, so it should be what the service returns. Could you please provide a breaking example of the problem.

**Comment by dottodot** [comment]
using feathers-client the follow request return 50 items and a total of 50 even though there are more records.
```
service.find({query: {$limit: 50, $skip: 0}})
```
on the feathers service I have 
```
exports.after = {
  all: [],
  find: [hooks.populate({
    schema
  })],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};
```
with a schema of 
```
module.exports = {
  include: [{
    service: 'images',
    nameAs: 'image_s3',
    parentField: 'image_s3',
    childField: '_id',
    query: {
      $select: ['key', 'version']
    }
  },{
    service: 'terms',
    nameAs: 'materialType',
    parentField: 'materialType',
    childField: '_id',
    query: {
      $select: ['name', 'weight', 'price'],
      $sort: {
        weight: 1
      }
    }
  }]
}

```

**Comment by eddyystop** [comment]
Could you copy here the contents of your services/replace-items.js ? Thanks.

**Comment by dottodot** [comment]
```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = function (hook, items) {
  if (hook.type === 'before') {
    hook.data = items;
  } else if (hook.method === 'find' && hook.result && hook.result.data) {
    hook.result.data = Array.isArray(items) ? items : [items];
  } else {
    hook.result = items;
  }
};

module.exports = exports['default'];
```

**Comment by dottodot** [comment]
@eddyystop Apologies my fault I was using 

```
const hooks = require('feathers-hooks');
```
instead of 
```
const hooks = require('feathers-hooks-common');
```

**Comment by eddyystop** [comment]
No problem as long as we found the problem. ;)

**Pull request merged**
