### PR TITLE
Added support for iff().else(hook1, hook2, ...)

### PR DESCRIPTION
**Pull request by eddyystop**
- Implemented support
- Updated tests.

### CODE REVIEW

**Comment by daffl** [comment]
This looks good. One thing for the tests is that you can now `return` a Promise in a test in Mocha 3. So something like

```js
it('calls async hook function if aync predicate truthy', (done) => {
  const result = hooks.iff(() => new Promise(resolve => resolve(true)), hookFcnAsync)(hook);

  if (result && typeof result.then === 'function') {
   result.then(result1 => {
      assert.deepEqual(result1, hookAfter);
      assert.equal(hookFcnAsyncCalls, 1);
      assert.deepEqual(result1, hookAfter);

      done();
    });
  } else {
    assert.fail(true, false, 'promise unexpectedly not returned');
    done();
  }
});
```

Would now look like

```js
it('calls async hook function if aync predicate truthy', () => {
  const result = hooks.iff(() => new Promise(resolve => resolve(true)), hookFcnAsync)(hook);

  if (result && typeof result.then === 'function') {
    return result.then(result1 => {
      assert.deepEqual(result1, hookAfter);
      assert.equal(hookFcnAsyncCalls, 1);
      assert.deepEqual(result1, hookAfter);
    });
  } else {
    assert.fail(true, false, 'promise unexpectedly not returned');
  }
});
```

The advantage is that you won't have to call `done` all the time and it catches all errors (the previous example with `done` would just time out if there was an assertion error).

**Comment by eddyystop** [comment]
Good news about returning Promises.

**Comment by daffl** [comment]
:shipit:

**Comment by daffl** [comment]
Actually by shipit I mean good go merge 😉 I was going to work on finishing up some smaller changes I have locally this weekend and then we can make a 2.1.0 release.

**Pull request merged**
