### PR TITLE
Changed tests for chai 4.0.0

### PR DESCRIPTION
**Pull request by eddyystop**
assert now does not compare time objects. A .getTime() is needed.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! Didn't Greenkeeper make a PR for the latest of Chai? I'm not sure what to do with all the other Chai PRs at the moment to be honest. Looks like the `sinon-chai` they are using hasn't been updated yet. Any ideas if we can still update them?

**Comment by eddyystop** [comment]
I wasn't sure if I should tack my PR onto Greenkeeper's. I guess I should from now on. Greenkeeper's PR was automatically (I think) closed when I pushed mine.

Which other Chai PRs are you referring to? I deleted the emails for repos other than one's I though I should handle.

**Comment by daffl** [comment]
I meant the Chai 4 PRs for other projects (like https://github.com/feathersjs/feathers-authentication-ldap/pull/12).

**Comment by eddyystop** [comment]
It seems like the <4 in the peer-dependencies may be removed according to https://github.com/domenic/sinon-chai/issues/97 .

Their issue has been outstanding 4 days. Maybe give them some more time?

**Pull request merged**
